ALTER TABLE CITY
ADD COLUMN CAPITAL BIT(1) NULL DEFAULT 0 AFTER STATE_ID,
ADD COLUMN COASTAL BIT(1) NULL DEFAULT 0 AFTER CAPITAL;

ALTER TABLE `STATE`
ADD COLUMN `COASTAL` BIT(1) NULL DEFAULT 0 AFTER `COUNTRY_ID`;
