CREATE TABLE `MEDICO_CONTRATO_ANEXO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MEDICO_ID` int(11) NOT NULL,
  `CONTRATO_ANEXO_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_MCA_MEDICO_ID` (`MEDICO_ID`),
  KEY `FK_MCA_CONTRATO_ANEXO_ID` (`CONTRATO_ANEXO_ID`),
  CONSTRAINT `FK_MCA_CONTRATO_ANEXO_ID` FOREIGN KEY (`CONTRATO_ANEXO_ID`) REFERENCES `CONTRATO_ANEXO` (`ID`),
  CONSTRAINT `FK_MCA_MEDICO_ID` FOREIGN KEY (`MEDICO_ID`) REFERENCES `MEDICO` (`ID`)
)