SET SQL_SAFE_UPDATES = 0;

UPDATE medico
SET STATUS='P'
WHERE medico.EMAIL_VALIDADO = true AND medico.CADASTRO_COMPLETO is NULL;

UPDATE medico
SET STATUS='P'
WHERE medico.EMAIL_VALIDADO = true AND medico.CADASTRO_COMPLETO = false;

UPDATE medico
SET STATUS='P'
WHERE medico.EMAIL_VALIDADO = false;

SET SQL_SAFE_UPDATES = 1;