CREATE TABLE `contrato_anexo` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTRATO_ID` int(11) NOT NULL,
  `NOME_ANEXO` varchar(200) DEFAULT NULL,
  `TIPO_ANEXO` varchar(200) DEFAULT NULL,
  `VALIDADO` bit(1) DEFAULT NULL,
  `OBSERVACAO_VALIDACAO` longtext,
  `BASE64_ANEXO` longblob,
  `USUARIO_INC` longtext NOT NULL,
  `USUARIO_ALT` longtext NOT NULL,
  `USUARIO_DEL` longtext,
  `DATA_USUARIO_INC` datetime NOT NULL,
  `DATA_USUARIO_ALT` datetime NOT NULL,
  `DATA_USUARIO_DEL` datetime DEFAULT NULL,
  `EXCLUIDO` bit(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CA_CONTRATO_idx` (`CONTRATO_ID`),
  CONSTRAINT `FK_CA_CONTRATO` FOREIGN KEY (`CONTRATO_ID`) REFERENCES `contrato` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB