CREATE TABLE `CURSO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `DATA_VENCIMENTO` datetime NOT NULL,
  `DATA_USUARIO_ALT` datetime NOT NULL,
  `DATA_USUARIO_DEL` datetime DEFAULT NULL,
  `DATA_USUARIO_INC` datetime NOT NULL,
  `USUARIO_INC` longtext NOT NULL,
  `USUARIO_DEL` longtext,
  `USUARIO_ALT` longtext NOT NULL,
  `EXCLUIDO` bit(1) NOT NULL,
  PRIMARY KEY (`ID`)
)