ALTER TABLE `EVENTO` CHANGE `DATA_HORA_INICIO` `DATA_INICIO` date NOT NULL;
ALTER TABLE `EVENTO` CHANGE `DATA_HORA_FIM` `DATA_FIM` date NOT NULL;

ALTER TABLE `EVENTO` ADD COLUMN `HORA_INICIO` TIME NOT NULL;
ALTER TABLE `EVENTO` ADD COLUMN `HORA_FIM` TIME NOT NULL;