CREATE TABLE `PREFERENCES_WEEKDAY` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `MONDAY` bit(1) DEFAULT b'0',
    `TUESDAY` bit(1) DEFAULT b'0',
    `WEDNESDAY` bit(1) DEFAULT b'0',
    `THURSDAY` bit(1) DEFAULT b'0',
    `FRIDAY` bit(1) DEFAULT b'0',
    `SATURDAY` bit(1) DEFAULT b'0',
    `SUNDAY` bit(1) DEFAULT b'0',
    PRIMARY KEY (`ID`),
    UNIQUE KEY (`ID`)
);



CREATE TABLE `PREFERENCES_PERIODO` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `MANHA` bit(1) DEFAULT b'0',
    `TARDE` bit(1) DEFAULT b'0',
    `NOITE` bit(1) DEFAULT b'0',
    `CINDERELA` bit(1) DEFAULT b'0',
    PRIMARY KEY (`ID`),
    UNIQUE KEY (`ID`)
);



CREATE TABLE `PREFERENCES_SETOR` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `CONSULTORIO` bit(1) DEFAULT b'0',
    `OBSERVACAO` bit(1) DEFAULT b'0',
    `EMERGENCIA` bit(1) DEFAULT b'0',
    `PEDIATRIA` bit(1) DEFAULT b'0',
    PRIMARY KEY (`ID`),
    UNIQUE KEY (`ID`)
);



CREATE TABLE `PREFERENCES_MEDIC` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`MEDIC_ID` int(11) NOT NULL,
    `PREFERENCES_WEEKDAY_ID` int(11) DEFAULT NULL,
	`PREFERENCES_PERIODO_ID` int(11) DEFAULT NULL,
	`PREFERENCES_SETOR_ID` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE KEY (`ID`)
);



CREATE TABLE `PREFERENCES_LOCALITY` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`STATE_ID` int(11),
	`PREFERENCES_MEDIC_ID` int(11),
    `CAPITAL` bit(1) DEFAULT b'0',
	`COUNTRYSIDE` bit(1) DEFAULT b'0',
	`COASTAL` bit(1) DEFAULT b'0',
	PRIMARY KEY (`ID`),
	UNIQUE KEY (`ID`)
);




