CREATE TABLE `MEDICO_CURSO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MEDICO_ID` int(11) NOT NULL,
  `CURSO_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_MC_MEDICO_idx` (`MEDICO_ID`),
  KEY `FK_MC_CURSO_idx` (`CURSO_ID`),
  CONSTRAINT `FK_MC_CURSO` FOREIGN KEY (`CURSO_ID`) REFERENCES `CURSO` (`ID`),
  CONSTRAINT `FK_MC_MEDICO` FOREIGN KEY (`MEDICO_ID`) REFERENCES `MEDICO` (`ID`)
);