ALTER TABLE `MEDICO`
    ADD COLUMN `NUMERO_CRM_ADICIONAL` VARCHAR(20) DEFAULT NULL AFTER `NUMERO_CRM` ;

ALTER TABLE `MEDICO`
    ADD COLUMN `UF_CONSELHO_MEDICO_ADICIONAL` VARCHAR(40) DEFAULT NULL AFTER `NUMERO_CRM_ADICIONAL`;
