CREATE TABLE `BLOQUEIO_MEDICO_CONTRATO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MEDICO_ID` int(11) NOT NULL,
  `CONTRATO_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BMC_MEDICO_ID` (`MEDICO_ID`),
  KEY `FK_BMC_CONTRATO_ID` (`CONTRATO_ID`),
  CONSTRAINT `FK_BMC_CONTRATO` FOREIGN KEY (`CONTRATO_ID`) REFERENCES `CONTRATO` (`ID`),
  CONSTRAINT `FK_BMC_MEDICO` FOREIGN KEY (`MEDICO_ID`) REFERENCES `MEDICO` (`ID`)
);