ALTER TABLE `MEDICO`
ADD COLUMN `BIOMETRY_PUBLIC_KEY` VARCHAR(2000) NULL DEFAULT NULL AFTER `TELEFONE`;

ALTER TABLE `MEDICO`
    ADD COLUMN `BIOMETRY_SIGNATURE` VARCHAR(2000) NULL DEFAULT NULL AFTER `BIOMETRY_PUBLIC_KEY`;