export enum Status {
    OK = 'OK',
    PENDING = 'PENDING',
    REJECTED = 'REJECTED',
    ADJUSTED = 'ADJUSTED',
    CONTESTED = 'CONTESTED',
    CORRECTION = 'CORRECTION',
    ATTENDANCE = 'ATTENDANCE',
    PROGRAMMED = 'PROGRAMMED',
    ADJUSTED_ADMIN = 'ADJUSTED_ADMIN',
    NOT_REGISTERED = 'NOT_REGISTERED',
    ADJUSTED_DOCTOR = 'ADJUSTED_DOCTOR',
    CANCELED = 'CANCELED'
}
